### ISSUE TITLE
The docstring for send-request* is now outdated?

### ISSUE THREAD

**Issue by MageMasher** [cognitect-labs/aws-api#100]
The docstring for `c.a.client/send-request*` states it is `*BLOCKING*` but as of [this commit](https://github.com/cognitect-labs/aws-api/commit/c29a84f53983abb396bbcdc0d4651f6c3daba044) this (I believe) is now once again non-blocking.

 Stu modified this section [2 days ago](https://github.com/cognitect-labs/aws-api/commit/0432b525d53628c42a7e0dee20293f1e2c9812b9).

**Comment by dchelimsky** [comment]
The call to `(credentials/fetch credentials)` [here](https://github.com/cognitect-labs/aws-api/commit/c29a84f53983abb396bbcdc0d4651f6c3daba044#diff-d31fc7fc5dbe82643e43459c2db6eb57L71) is still blocking.
