### ISSUE TITLE
S3 CopyObject does not copy objects larger than 5G

### ISSUE THREAD

**Issue by jsyrjala** [cognitect-labs/aws-api#107]
S3 CopyObject refuses to copy objects that are larger than 5G which is a limitation in S3.

You can implement a workaround for this using MultiPartUploads with this kind of code:
https://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjctsUsingLLJavaMPUapi.html

Are these kinds of operations out-of-scope for aws-api?

**Comment by dchelimsky** [comment]
Yes, @jsyrjala, this is out of scope. aws-api is constrained to operations described in service descriptors provided by aws, and the low level java API is not part of that. We do hope that other libraries will appear to handle these sorts of cases that require custom solutions.
