### ISSUE TITLE
Calling `(aws/client {:api :sqs})` increases the count of open file descriptors.

### ISSUE THREAD

**Issue by Jaretbinford** [cognitect-labs/aws-api#109]
## Dependencies

``` clojure
{:deps {com.cognitect.aws/api               {:mvn/version "0.8.345"}
        com.cognitect.aws/endpoints         {:mvn/version "1.1.11.590"}
        com.cognitect.aws/s3                {:mvn/version "714.2.430.0"}}}
```

## Description with failing test case

Calling `(aws/client {:api :sqs})` increases the count of open file descriptors. 

```
[ec2-user@ip-10-213-1-197 ~]$ cat /proc/sys/fs/file-nr
896 0   1559195
;;making calls to (aws/client {:api :sqs})
[ec2-user@ip-10-213-1-197 ~]$ cat /proc/sys/fs/file-nr
10456 0   1559195
```

This file descriptor leak reached a point where it exhausted the limit and system restart was required.  After identifying the leak, customer was able to resolve by adding a delay:

```clojure
(def sqs-client
(delay (aws/client {:api :sqs})))
```

**Comment by kulminaator** [comment]
(aws/stop client-reference)  closes the http client and related handles it seems. should be advised in the docs ? the "close" would be much more conventional though

**Comment by dchelimsky** [comment]
@kulminaator is https://github.com/cognitect-labs/aws-api#http-client missing something that would make it more clear?

**Comment by kulminaator** [comment]
I suppose that block is actually clear enough. 
Maybe people trip on it because they are used to `with-open` and this interface doesn't seem compatible with it ?

**Comment by dchelimsky** [comment]
Released today: https://github.com/cognitect-labs/aws-api/blob/master/CHANGES.md#08430--2020-02-10
