### ISSUE TITLE
Remove commons-codec dependency

### ISSUE THREAD

**Issue by puredanger** [cognitect-labs/aws-api#113]
I noticed that aws-api is pulling in commons-codec (a ~300kb library) for a single method (Hex/encodeHex). Because I am an obsessive weirdo, I implemented an almost as fast Clojure-only version of that method and got rid of the dep, which you can find in a branch at https://github.com/cognitect-labs/aws-api/compare/remove-codec-dep.

This impl is about 1.7x the time for a 30 character string (in the range of 10s of nanoseconds). I suspect this is negligible compared to talking to network services. I'd rather lose the dep. But I will let you make the call!

It's possible that the Clojure version could be faster (it could certainly be as fast if I used Java but that seemed bad in other ways), but I suspect it's hard to do much better than this.

**Comment by dchelimsky** [comment]
I merged to master and deleted the remote branch. Thanks @puredanger!
