### ISSUE TITLE
Build source available somewhere?

### ISSUE THREAD

**Issue by brandonbloom** [cognitect-labs/aws-api#116]
First of all: Thank you! This is an amazing library.

I'm wondering if the source code for the build/package/release process is available or can be made available. I'm assuming that the service.edn files are a straight translation of the *-normal.json files, but I'm curious to see how the specs.clj files are generated.

Cheers,
Brandon

**Comment by dchelimsky** [comment]
Thanks for your interest @brandonbloom, but the generator is not open source.
