### ISSUE TITLE
Problem sending email with SESV2

### ISSUE THREAD

**Issue by a-luz** [cognitect-labs/aws-api#129]
## Dependencies
``` clojure
{:deps {com.cognitect.aws/api       {:mvn/version "0.8.408"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.11.682"}
        com.cognitect.aws/sesv2        {:mvn/version "783.2.590.0"}}}
```

## Description with failing test case
I am trying to send a simple e-mail using this library. After going through the [sesv2 api description](https://github.com/aws/aws-sdk-js/blob/master/apis/sesv2-2019-09-27.normal.json) I tried to create a function to send the e-mail (code below), and it returns a `:cognitect.anomalies/incorrect` (which I believe means there's something wrong with my code), but the message that comes along with the anomaly is nil.

### Code created
```clojure
;; Declaring a client (aws credentials are set as env. variables)
(def sesv2-client-test  (aws/client {:api    :sesv2
                             :region "us-east-1"}))

;; Function that is supposed to send the e-mail
(defn send-test-email 
  []
  (aws/invoke sesv2-client-test {:op :SendEmail :request
                                          { ;; :Source "ses_verified_email@gmail.com"
                                           :Destination {:ToAddresses ["valid_email@gmail.com"]}
                                           :Content     {:Simple {:Body    {:Text {:Charset "UTF-8"
                                                                                   :Data    "test email body"}}
                                                                  :Subject {:Charset "UTF-8"
                                                                            :Data    "test email"}}}}}))
```
### Function returns
```clojure
{:message nil, :cognitect.anomalies/category :cognitect.anomalies/incorrect}
```

At first, I had not set the `:Source` key, since it isn't described in the file linked above, but after seeing some example codes in javascript, I decided to include it but still getting the error with `:message nil`. I feel like I might be missing something else in the request, but can't figure out what.

Any directions would be appreciated!
Thank you

**Comment by dchelimsky** [comment]
What does `(meta (send-test-email))` look like?

**Comment by dchelimsky** [comment]
Also, `(aws/doc sesv2-client-test :SendEmail)` should give you clearer direction than https://github.com/aws/aws-sdk-js/blob/master/apis/sesv2-2019-09-27.normal.json.

**Comment by dchelimsky** [comment]
I ran your code as/is and got the same response from aws-api, and also inspected the raw payload coming back from AWS. Here's the body: `"{\"message\":null}"`. So at least aws-api is returning the right thing (what AWS sent).

Check https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html and maybe the AWS logs.

**Comment by a-luz** [comment]
Thank you very much for the replies.

It turns out I was missing the `:FromEmailAddress` key. Don't know how I missed that..

**Comment by dchelimsky** [comment]
Sadly, `FromEmailAddress` is [not required according to AWS docs](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html#API_SendEmail_RequestSyntax). It is also not listed as [required in the descriptor](https://github.com/aws/aws-sdk-js/blob/master/apis/sesv2-2019-09-27.normal.json#L3661-L3666), which is why it ends up not listed as required in the result of `cognitect.aws.client.api/doc`:

```
...
Request

{:FromEmailAddress string,
 :Destination
 {:ToAddresses [:seq-of string],
  :CcAddresses [:seq-of string],
  :BccAddresses [:seq-of string]},
 :ReplyToAddresses [:seq-of string],
 :FeedbackForwardingEmailAddress string,
 :Content
 {:Simple
  {:Subject shape/Content,
   :Body {:Text shape/Content, :Html shape/Content}},
  :Raw {:Data blob},
  :Template {:TemplateArn string, :TemplateData string}},
 :EmailTags [:seq-of {:Name string, :Value string}],
 :ConfigurationSetName string}

Required

[:Destination :Content]
...
```

How was it that figured out that this is what was missing?

**Comment by a-luz** [comment]
No having a key to specify the sending email was kind of bugging me from the start, so I thought that might be the problem.
My main issue was that for some reason I simply did not assimilate the `FromEmailAddress: ` when reading through the sesv2.json file... by using `(aws/doc sesv2-client-test :SendEmail)` the inputs were much clearly displayed and I was able to see that I skipped that key.

**Comment by dchelimsky** [comment]
OK. Thanks for following up. I'm going to close this, as there's nothing practical for us to do. You may consider filing an issue w/ AWS since their docs don't indicate that `FromEmailAddress` is required, but the behaviour suggests otherwise.
