### ISSUE TITLE
Dynamodb transaction API methods missing

### ISSUE THREAD

**Issue by tvanhens** [cognitect-labs/aws-api#13]
The dynamodb client is missing the new `Transact` methods that were added recently:

https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/

I'm assuming this is due to needing to re-run the generators, however, I wanted to create an issue since there are actually 2 versions of the dynamodb descriptors: `2011-12-05` and `2012-08-10` - it doesn't look like the version with the `Transaction` methods is getting generated.

**Comment by dchelimsky** [comment]
They're in `com.cognitect.aws/dynamodb-675.2.365.0`, which was released over the weekend, but you had no way to know that if you didn't search https://search.maven.org/. That's your best bet to see what the latest is. You can also check [https://github.com/cognitect-labs/aws-api/blob/master/doc/latest-releases.md](https://github.com/cognitect-labs/aws-api/blob/master/doc/latest-releases.md), but that may go away if/when we choose a different way to convey release information.

**Comment by dchelimsky** [comment]
Also, just FYI, in the face of more than one descriptor, we always generate from the later one. In this case, it's `2012-08-10`. Cheers.
