### ISSUE TITLE
Support for DynamoDB indexes querying?

### ISSUE THREAD

**Issue by benfle** [cognitect-labs/aws-api#138]
Hi David,

am I correct that there is no way currently to query DynamoDB indexes? The Java SDK provides this functionality through the `getTable` method but it is not currently supported in the client and I couldn't find a way around it.

It might be a good idea to maintain a list of the important unsupported features on the README page so people don't start development and realize half-way through that they're stuck :)

Two features that I have been missing so far are URL signing for S3 and the DDB index queries.

Cheers,
Benoît.

**Comment by dchelimsky** [comment]
Hey @benfle! With over 200 services and 1000s of operations and no comprehensive machine readable listing of them, it's just not feasible for us to generate and maintain such a list. I added a "missing operation" label for now, and I'll discuss other possibilities w/ other maintainers.

**Comment by dchelimsky** [comment]
@benfle the `:Query` op supports `:IndexName`. Are you looking for something else?

**Comment by dchelimsky** [comment]
See https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html re: querying indexes through the API. Closing this, but if I'm missing something, please let me know and I'll re-open it.

**Comment by benfle** [comment]
Yes, it looks like it might work with this `Query` operation. I missed that. Thanks!
