### ISSUE TITLE
Memory leak when client is not re-used and validate-requests is called

### ISSUE THREAD

**Issue by tamasjung-fc** [cognitect-labs/aws-api#143]
In the latest version although the client re-uses the http-client by default it returns a new object every time for `(aws/client {:api :s3})` then `(aws/validate-requests s3 true)` pins the client forever here:

https://github.com/cognitect-labs/aws-api/blob/master/src/cognitect/aws/client/api/async.clj#L17

**Comment by dchelimsky** [comment]
Fixed on master. Will be part of the next release (probably today).

**Comment by dchelimsky** [comment]
Released in 0.8.469.
