### ISSUE TITLE
Missing ses API anything we can do to get it added / supported ?

### ISSUE THREAD

**Issue by olymk2** [cognitect-labs/aws-api#147]
Looking through the supported services listed here I can see you have sesv2 but not sesv1.

https://github.com/cognitect-labs/aws-api/blob/ecad8a3010bc6c4dd3ac3005b15c8a6020fbee2a/latest-releases.edn#L526 

An example would be GetSendStatistics which is not in sesv2, alternatively any info available on the steps required to adding in missing API end points functionality.
https://docs.aws.amazon.com/ses/latest/APIReference/API_GetSendStatistics.html#API_GetSendStatistics_Errors

**Comment by dchelimsky** [comment]
aws-api supports services for which descriptors exist here: https://github.com/aws/aws-sdk-js/tree/master/apis. As you can see sesv2 is not listed there, so we'd need a different strategy just to support this one service, which is not on our roadmap (at least not yet).

I wonder why the old APIs are not supported by v2, and wonder if there's a new way to get the same information.

**Comment by dchelimsky** [comment]
Well, look at this: https://github.com/aws/aws-sdk-js/blob/master/apis/email-2010-12-01.normal.json#L649

The service you want is:

```clojure
com.cognitect.aws/email
 {:mvn/version "770.2.568.0",
  :aws/serviceFullName "Amazon Simple Email Service"}
```

**Comment by olymk2** [comment]
Thanks a lot for pointing me at that nice simple fix :)

**Comment by dchelimsky** [comment]
> Thanks a lot for pointing me at that nice simple fix :)

You're welcome! I'm just relieved that we could solve your problem without rewriting our generator :)
