### ISSUE TITLE
Request required member names don't always match uri template names

### ISSUE THREAD

**Issue by arohner** [cognitect-labs/aws-api#151]
## Dependencies

``` clojure
{:deps {com.cognitect.aws/api       {:mvn/version "0.8.474"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.11.753"}
       com.cognitect.aws/kafka {:mvn/version "793.2.626.0"}}}
```

(the dependencies are funky here. I'm working off a fork that contains a fix for #146, but the problem will exist on master once 146 is fixed)

## Description with failing test case

```
(let [kafka (aws/client {:api :kafka :region :eu-west-2})]
    (aws/invoke kafka {:op :CreateConfiguration :request {:Name "test"
                                                            :KafkaVersions ["2.2.1"]
                                                            :ServerProperties (->> ["auto.create.topics.enable=false"
                                                                                    "default.replication.factor=3"
                                                                                    "delete.topic.enable=false"
                                                                                    "min.insync.replicas=2"]
                                                                                   (clojure.str/join "\n"))
                                                            :Description "cognitect test Configuration"}}
    (aws/invoke kafka {:op :DescribeConfigurationRevision :request {:Arn <the-returned-arn> :Revision 1})))
```

The request fails with 
```
{:request (#object[cognitect.aws.client.Client 0x11e67eb9 "cognitect.aws.client.Client@11e67eb9"] {:op :DescribeConfigurationRevision, :request {:Arn "arn:aws:kafka:eu-west-2:623060147434:configuration/basic/51bce36e-67c2-4d69-9e61-a6f50759d54e-2", :Revision 1}}), :response {:message "Missing required request parameters: [arn]", :cognitect.anomalies/category :cognitect.anomalies/incorrect}}
```
`:Arn` was supplied, but `cognitect.aws.protocols.rest/serialize-uri` fails to include Arn in the string. Debug printing shows the request made was to `/v1/configurations/revision/` rather than the expected `/v1/configurations/<arn>/revisions/1` 

This is because in the model, (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-models/src/main/resources/models/kafka-2018-11-14-model.json), DescribeConfigurationRevision is specified as

```
"DescribeConfigurationRevision": {
      "name": "DescribeConfigurationRevision",
      "http": {
        "method": "GET",
        "requestUri": "/v1/configurations/{arn}/revisions/{revision}",
        "responseCode": 200
      },
      "input": {
        "shape": "DescribeConfigurationRevisionRequest"
      },

...
    "DescribeConfigurationRevisionRequest": {
      "type": "structure",
      "members": {
        "Arn": {
          "shape": "__string",
          "location": "uri",
          "locationName": "arn",
          "documentation": "\n            <p>The Amazon Resource Name (ARN) that uniquely identifies an MSK configuration and all of its revisions.</p>\n         "
        },
        "Revision": {
          "shape": "__long",
          "location": "uri",
          "locationName": "revision",
          "documentation": "\n            <p>A string that uniquely identifies a revision of an MSK configuration.</p>\n         "
        }
      },
      "required": [
        "Revision",
        "Arn"
      ]


```

Note that the DescribeConfigurationRevision operation specifies `arn` in the uri, but the Request object specifies a member named `Arn` which will be inserted into the uri as `arn`. 

`cognitect.aws.protocols.rest/serialize-uri` assumes that the uri-template name matches the Request's member name, which isn't always the case.

**Comment by dchelimsky** [comment]
> cognitect.aws.protocols.rest/serialize-uri assumes that the uri-template name matches the Request's member name, which isn't always the case.

`serialize-uri` does not make that assumption. The description for "Arn" includes `"location": "uri", "locationName": "arn"`, which upstream code ([partition-args](https://github.com/cognitect-labs/aws-api/blob/c1f9393cf6399d35b140307abf96e95ebe6c627f/src/cognitect/aws/protocols/rest.clj#L144-L159)) uses to format the `args` argument to `serialize-uri`, which it sees in the form:

```clojure
{:arn "<arn>", :revision <long>})
```

Here is the call to `serialize-uri` with the inputs from your example (with private info replaced with tokens):

```clojure
(serialize-uri
 "/v1/configurations/{arn}/revisions/{revision}"
 {:type "structure", :members {:Arn {:shape "__string", :location "uri", :locationName "arn"}, :Revision {:shape "__long", :location "uri", :locationName "revision"}}, :required ["Revision" "Arn"]}
 {:arn "arn:aws:kafka:us-east-1:<account>:configuration/test/<uuid>", :revision 1})
;; => "/v1/configurations/arn%3Aaws%3Akafka%3Aus-east-1%3A<account>%3Aconfiguration%2Ftest%2F<uuid>/revisions/1"
```

That said, I get a different error with "The request signature we calculated does not match the signature you provided.", which I'll look into, but this issue as presented is not an issue, so closing.
