### ISSUE TITLE
Missing Personalize Events endpoints

### ISSUE THREAD

**Issue by castiel-moovup** [cognitect-labs/aws-api#154]
## Dependencies

``` clojure
{:deps {com.cognitect.aws/personalize {:mvn/version "807.2.729.0"}
        com.cognitect.aws/personalize-events {:mvn/version "807.2.729.0"}
        com.cognitect.aws/s3 {:mvn/version "809.2.734.0"}}}
```

## Description

Code:
```clojure
(require '[cognitect.aws.client.api :as api])
(-> (api/client {:api :personalize-events})
    (api/ops)
    (keys))
```

Expected response:
```clojure
(:PutEvents :PutItems :PutUsers)
```

Actual response:
```clojure
(:PutEvents)
```

`PutItems` and `PutUsers` operations are available in latest AWS js API definition:
https://github.com/aws/aws-sdk-js/blob/master/apis/personalize-events-2018-03-22.normal.json

**Comment by dchelimsky** [comment]
`:PutItems` and `:PutUsers` were added since the last time we updated the service releases. I just updated all of the service releases, including `com.cognitect.aws/personalize-events {:mvn/version "809.2.784.0"}`, and you can see those two new ops are available now.

**Comment by castiel-moovup** [comment]
@dchelimsky Thanks a lot!
