### ISSUE TITLE
Please add support for `sso-admin`

### ISSUE THREAD

**Issue by arohner** [cognitect-labs/aws-api#159]
There isn't a `com.cognitect.aws/sso-admin` yet, based on https://github.com/aws/aws-sdk-js/blob/master/apis/sso-admin-2020-07-20.normal.json

Separately, is it possible to build and deploy new service deps without waiting for an official release? I couldn't find any code to perform these builds.

**Comment by dchelimsky** [comment]
There was a bug in the generator that was causing it to fail to generate libs for new services as they appear. I fixed it and am running the generator now, and will follow up as soon as sso-admin is released.

The generator is not a public project so it is not possible for you to build and deploy your own deps.

**Comment by dchelimsky** [comment]
`{:deps {com.cognitect.aws/sso-admin {:mvn/version "810.2.797.0"}}}`
