### ISSUE TITLE
broken pipe -> `:fault` -> no retry

### ISSUE THREAD

**Issue by NickeZ** [cognitect-labs/aws-api#162]
Thanks for providing a great lib. I have a question about the error type of "broken pipe" that occurred when we wrote to kinesis.

It is my understanding that "broken pipe" is a temporary issue in the client or connection between the client and the server and that it should be retried automatically. But reading the description of anomalies it is being mapped to a type that "shouldn't" be retried.

We are considering adding `:fault` to the list of retried anomalies, but that seems wrong according to the description of `:fault`. What do you suggest?

## Dependencies

``` clojure
  com.cognitect.aws/api {:mvn/version "0.8.423"
                         :exclusions [org.eclipse.jetty/jetty-util]}
  org.eclipse.jetty/jetty-util {:mvn/version "9.4.26.v20200117"}
  com.cognitect.aws/endpoints {:mvn/version "1.1.11.710"}
  com.cognitect.aws/kinesis {:mvn/version "770.2.568.0"}
  com.cognitect.aws/ssm {:mvn/version "784.2.595.0"}
  com.cognitect.aws/sqs {:mvn/version "770.2.568.0"}
  com.cognitect.aws/lambda {:mvn/version "780.2.584.0"}
  com.cognitect.aws/dynamodb {:mvn/version "770.2.568.0"
                              :aws/serviceFullName "Amazon DynamoDB"}

```

## Description with failing test case

We got a failure in production that didn't lead to retries because AFAIU `:fault` is not retried by default.

```
"cause": "Operation failed",
    "data": {
      "cognitect.anomalies/category": "cognitect.anomalies/fault",
      "cognitect.anomalies/message": "Broken pipe",
      "cognitect.http-client/throwable": "java.io.IOException: Broken pipe"
    }
```

Sorry that I don't have a reproducible example, but I think it is clear what has happened.

**Comment by dchelimsky** [comment]
You can solve this using a custom `retriable?` fn:

https://cognitect-labs.github.io/aws-api/cognitect.aws.client.api-api.html#cognitect.aws.client.api/client

https://github.com/cognitect-labs/aws-api/blob/fc12f595008a55dd6662a95af0e9172eef1e3bc5/src/cognitect/aws/client/api.clj#L52-L57

### More context

Unfortunately, there is no spec (at least we're not aware of one) for the [aws specs](https://github.com/aws/aws-sdk-js/tree/master/apis) on which aws-api is based, so we have no way to deterministically interpret error codes that come back from the 250+ aws services. Generalizing on `fault` as retriable would likely be incorrect at least some of the time.

I'm going to close this issue, but feel free to continue the conversation in comments here if you have more questions about it.
