### ISSUE TITLE
system-property-credentials-provider missing aws.sessionToken system property

### ISSUE THREAD

**Issue by digash** [cognitect-labs/aws-api#167]
Hi,

Trying to authenticate w/o sessionToken causes "The security token included in the request is invalid."
Adding session token property fixes this issue.

https://github.com/cognitect-labs/aws-api/blob/c1f9393cf6399d35b140307abf96e95ebe6c627f/src/cognitect/aws/credentials.clj#L205

It is also listed in [SystemProperyCredentialsProvide Java API](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/SystemPropertyCredentialsProvider.html)

Regards,
Dig

**Comment by dchelimsky** [comment]
Fixed in e333d5357de1c93551b902189ab7220e0f487a6b

**Comment by dchelimsky** [comment]
Released in aws-api 0.8.498
