### ISSUE TITLE
Reporting a typo in example

### ISSUE THREAD

**Issue by samrose** [cognitect-labs/aws-api#179]
I know you do not accept PR's, but I submitted this one just to pinpoint where the issue in the example is

https://github.com/cognitect-labs/aws-api/pull/178/files

Thanks for this great library!

**Comment by dchelimsky** [comment]
Updated in https://github.com/cognitect-labs/aws-api/commit/5843c22679f28dd70fa3180e5a2487ebab7eb770. Thanks!
