### ISSUE TITLE
prefer aws methods as functions

### ISSUE THREAD

**Issue by imajinos** [cognitect-labs/aws-api#18]
This is great, but I'd like to be able to import a namespace of aws service functions. Playing with ssm, I ended up writing code like this to get there:

```
(def ssm-client (aws/client {:api :ssm}))
(def ssm-operation (partial aws/invoke ssm-client))
(defn ssm [op request]
 (ssm-operation {:op op :request request}))

(def ssm-send-command (partial ssm :SendCommand))
(def ssm-list-commands (partial ssm :ListCommands))
(def ssm-list-command-invocations (partial ssm :ListCommandInvocations))
(def ssm-get-command-invocation (partial ssm :GetCommandInvocation))
```

This gives me functions that take the :request value as argument and allow my written-for-Amazonica pagination helper functions to work.*

What do you think?  Lots of room for helper functions unwrapping nested paginated results, too.
Today I wrote into a let..
 `responses (into [] (flatten (for [p response-pages] (for [r (:CommandInvocations p)] r))))`

**Comment by dchelimsky** [comment]
"one fn + data" is a fundamental concept of this library, and lots of other design decisions fall out of it, so this is unlikely to change. As you've shown, you can do what you propose in your own code, or even a separate library.
