### ISSUE TITLE
Bump to latest core.async 1.3.622

### ISSUE THREAD

**Issue by puredanger** [cognitect-labs/aws-api#194]
There is a new core.async version (1.3.622) that depends on a new tools.analyzer.jvm, that depends on a new tools.analyzer that fixes warnings from overlapping the existing functions there update-keys and update-vals if you happen to use all this stuff with 1.11.0-alpha2+. If you could bump the dep, that would be cool.

**Comment by fogus** [comment]
Upgraded in v0.8.524
