### ISSUE TITLE
How to invoke a private API?

### ISSUE THREAD

**Issue by nickstares** [cognitect-labs/aws-api#204]
Hello, first time using `aws-api` and I I am trying to invoke a [private api](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-api-test-invoke-url.html
) 
Basically the equivalent of hitting
`https://{restapi-id}.execute-api.{region}.amazonaws.com/{stage}`
 With a GET or POST request. How should I go about doing this? I took a shot in the dark but I don't know what the value for `:api` should be:
```clojure
  (aws/client {:api :apigateway
               :region "us-east-1"
               :endpoint-override {:hostname "ry8g3pqgz5"
                                   :path     "/prod/workflows"}}))
```
If I am able to build the client successfully, what would the Invoke `:op` be?

Any help much appreciated.

**Comment by dchelimsky** [comment]
I _think_ the `:hostname` should be `{restapi-id}.execute-api.{region}.amazonaws.com` and the path should be `{stage}/workflows`.

The `:op` is whatever operation you want to invoke. That'll get appended to the path.

Does that help @nickstares ?

**Comment by dchelimsky** [comment]
Closing this as the question is answered. Please feel free to comment if you have more questions.
