### ISSUE TITLE
Silent failure in XML parsing returns empty result from S3

### ISSUE THREAD

**Issue by bsless** [cognitect-labs/aws-api#205]
Thank you for your interest in helping to improve Cognitect's aws-api!

## Dependencies

``` clojure
 :deps {org.clojure/clojure {:mvn/version "1.10.3"}
        techascent/tech.ml.dataset {:mvn/version "6.053"}
        ;; techascent/tech.ml.dataset {:mvn/version "5.00"}
        com.cognitect.aws/api       {:mvn/version "0.8.539"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.12.110"}
        com.cognitect.aws/s3        {:mvn/version "814.2.991.0"}}
```

## Description with failing test case

When I include `techascent/tech.ml.dataset` an unreported conflict in xml dependencies causes a silent failure in the client and s3 operations fail

Also see
- reproduction repository: https://github.com/bsless/tmd-s3-repro
- https://github.com/techascent/tech.ml.dataset/issues/283

## Stack traces

Silent failure

**Comment by cnuernber** [comment]
I boiled things down in that issue to these dependencies:

```clojure
{:paths ["src" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.10.3"}
        com.fasterxml/aalto-xml {:mvn/version "1.3.1"}
        com.cognitect.aws/api       {:mvn/version "0.8.539"}
        com.cognitect.aws/endpoints {:mvn/version "1.1.12.110"}
        com.cognitect.aws/s3        {:mvn/version "814.2.991.0"}}
 :aliases
 {:test
  {:extra-paths ["test"]
   :extra-deps {org.clojure/test.check {:mvn/version "1.1.0"}
                io.github.cognitect-labs/test-runner
                {:git/tag "v0.5.0" :git/sha "48c3c67"}}}
  :build {:deps {io.github.seancorfield/build-clj
                 {:git/tag "v0.6.2" :git/sha "97c275a"}}
          :ns-default build}}}
```

**Comment by darin-reify** [comment]
I'm seeing this same behavior. Excluding `com.fasterxml/aalto-xml` fixed the problem for me too.

**Comment by darin-reify** [comment]
I did some more digging and it's (kinda expectedly) a problem in the `data.xml` library:

```bash
;; deps.edn
```

**Comment by dchelimsky** [comment]
Some context

* XMLInputFactory docs explicitly states that [only the true setting must be supported](https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLInputFactory.html#IS_NAMESPACE_AWARE) for IS_NAMESPACE_AWARE
* aalto, following the Java doc, [does not allow setting it to false](https://github.com/FasterXML/aalto-xml/blob/5deb3f4c3704c3d4047de8c3e9e3b1fb90f1d0c2/src/main/java/com/fasterxml/aalto/in/ReaderConfig.java#L66)
  * this means that even if we set it IS_NAMESPACE_AWARE to false, the aalto XMLInputFactory implementation is going to result in tags prefixed with namespaces if there is a namespace in the data
  * AWS sends XML payloads with namespaces in them, even though we don't need them

This doesn't leave great options for clojure.data.xml or aws-api, but we're looking into them.

**Comment by dchelimsky** [comment]
Fixed in org.clojure/data.xml-0.2.0-alpha8 and aws-api-0.8.596

**Comment by cnuernber** [comment]
Fixed by upstream change in [data.xml](https://github.com/clojure/data.xml/commit/d54b0a27c68abbdc3064e55ebd10942e6970c75e).
