### ISSUE TITLE
Sources for s3 resources do not contain license

### ISSUE THREAD

**Issue by ReilySiegel** [cognitect-labs/aws-api#208]
I am looking to include the s3 resources definition in the Guix distribution, as it is a dependency for building the Clojure CLI tools. As far as I can tell, the only place to obtain "sources" (I understand it is just EDN files) for the s3 resource definitions is at https://repo1.maven.org/maven2/com/cognitect/aws/s3/820.2.1083.0/s3-820.2.1083.0-sources.jar. This download does not include a copy of the ASL2.0 license. Is there another location where the sources for the service definitions can be downloaded, that includes a license file or disclaimer? Alternatively, is the code for generating these resource definitions from the AWS-sdk available? The policy for submitting packages to Guix is that the sources used to build the package must include an appropriate license disclaimer.

**Comment by emixa-d** [comment]
> Alternatively, is the code for generating these resource definitions from the AWS-sdk available? The policy for submitting packages to Guix is that the sources used to build the package must include an appropriate license disclaimer.

I don't think this is an _absolute_ requirement (*), it's just that Guix needs to know what licensing terms things are under, such that it can know if it is legal to redistribute, modify, etc. it, and including a copy of the license + license header alongside the source code (in this case these .edn files in the jar) is a very convenient and conventional way of doing this.

(*) E.g., I guess that if the license allows it and the licensing terms are on the website of the software project but not inside the source tarball or jar, that it might be ok as long as things are clear.

**Comment by dchelimsky** [comment]
I just released com.cognitect.aws/s3-821.2.1083.0, which includes the license. We'll do the same with all the other services soon (probably later today), but I wanted to get s3 out the door to resolve this issue first.

**Comment by ReilySiegel** [comment]
In the process of having this contributed to Guix, it seems like there is a further licensing issue. As this seems to be a derivitive work of aws-sdk-js (due to the generation of service files based on their definition, distributions must include the NOTICE.txt file found here: https://github.com/aws/aws-sdk-js/blob/master/NOTICE.txt.

It may also be necessary to include in the service files a notice that they are a modified form of the files in aws-sdk-js.
