### ISSUE TITLE
make com.cognitect/http-client source available

### ISSUE THREAD

**Issue by mpenet** [cognitect-labs/aws-api#23]
Hi, 

First of all: thanks for the  project. 

One of the deps listed is available on maven and seems to be Apache 2 licensed but the sources are not available anywhere as far as I can see. Would it be possible to publish these? 

https://search.maven.org/artifact/com.cognitect/http-client/0.1.87/jar

**Comment by dchelimsky** [comment]
The sources are in the released jar: http://central.maven.org/maven2/com/cognitect/http-client/0.1.87/.

**Comment by mpenet** [comment]
Sure, it's just not very convenient to have to dig inside jars.

**Comment by stuarthalloway** [comment]
Hi Max!  This is low priority absent a motivating use case. If we have failed to document the AWS lib in such a way that you need to read source of a dep to use it correctly, I would much prefer to start by improving the docs.

**Comment by mpenet** [comment]
Understood, feel free to close this, I was merely curious about that http library.

**Comment by stuarthalloway** [comment]
Hi Max!

Your request got me thinking about what I really want here, which is source access directly derived from project truth. I have spiked this out at https://github.com/stuarthalloway/reflector.

**Comment by mpenet** [comment]
Hi Stuart, 

Excellent :) Not exactly what I had in mind but I guess that will do. 
It's actually quite nice to have a real world example of `nav` usage. 

Thanks
