### ISSUE TITLE
AWS S3 Express One Zone (AWS S3 Directory)

### ISSUE THREAD

**Issue by brandonstubbs** [cognitect-labs/aws-api#248]
Hello,

I hope you're doing well! I wanted to bring to your attention some recent updates to the AWS S3 API, particularly regarding support for AWS S3 Express One Zone. It would be fantastic if aws-api could support this. Specifically, there are new API endpoints like `CreateSession` and `ListDirectoryBuckets`.

There also seems a harder change:
[`CreateBucket`
](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html)There is both the URI parameter `Bucket` (For the bucket name) and a new request body parameter `Bucket` (For the bucket type and redundancy)

Thanks!

**Comment by scottbale** [comment]
Done! [com.cognitect.aws/s3 version 857.2.1574.0](https://repo.maven.apache.org/maven2/com/cognitect/aws/s3/857.2.1574.0/)
