### ISSUE TITLE
Roadmap / plan for moving to AWS SDK v2

### ISSUE THREAD

**Issue by apchau25** [cognitect-labs/aws-api#251]
What is the plan / timeline for aws-api to migrate to aws sdk v2 , since AWS SDK v1.x will enter [EOS](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/) effective December 31, 2025

**Comment by 64BitChris** [comment]
I don't believe aws-api is built on the AWS SDK v1 or v2 - they make all their HTTP calls to the AWS APIs, but there is no dependency on the official AWS libraries.

That might be why they closed this issue - it might not be relevant.

**Comment by scottbale** [comment]
> I don't believe aws-api is built on the AWS SDK v1 or v2 - they make all their HTTP calls to the AWS APIs, but there is no dependency on the official AWS libraries.

That is correct. Thanks @64BitChris.
