### ISSUE TITLE
Add support for Neptune Data API

### ISSUE THREAD

**Issue by aamedina** [cognitect-labs/aws-api#253]
Would it be possible to add a new client for the Neptune Data API? 

Documentation:
https://docs.aws.amazon.com/neptune/latest/userguide/data-api.html

aws-sdk-js source:
https://github.com/aws/aws-sdk-js/blob/master/apis/neptunedata-2023-08-01.normal.json

**Comment by scottbale** [comment]
Done! [Here it is](https://repo.maven.apache.org/maven2/com/cognitect/aws/neptunedata/857.2.1574.0/).
