### ISSUE TITLE
Add support for the new WebSocket features in API Gateway

### ISSUE THREAD

**Issue by cjsauer** [cognitect-labs/aws-api#29]
Amazon recently announced [WebSocket support for API Gateway](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/). It looks to be a two part update according to the [aws-sdk-js descriptor files](https://github.com/aws/aws-sdk-js/tree/master/apis):

- `apigatewayv2-2018-11-29`
- `apigatewaymanagementapi-2018-11-29`

I'm eager to get a conversation going on how this could be incorporated into the `aws-api`. WebSocket + Datomic Ions could be a very powerful architecture.

**Comment by cjsauer** [comment]
Would I be incorrect in assuming that the addition of these two lines in the `latest-release.edn` file meant that this might now be possible with version `0.8.166`?

```
com.cognitect.aws/apigatewaymanagementapi "684.2.382.0",
com.cognitect.aws/apigatewayv2 "684.2.382.0",
```

[(Source)](https://github.com/cognitect-labs/aws-api/blob/master/latest-releases.edn#L11-L12)

**Comment by dchelimsky** [comment]
@cjsauer we periodically generate all the service libs from the api descriptors in https://github.com/aws/aws-sdk-js/tree/master/apis. When a new service appears in the source repo, we generate it, and that's what happened with the two you point out. I haven't looked into WebSocket support yet, but my guess would be that we're going to need to update the `api` lib to handle it. Feel free to try it out and report your experience here, but I'd be (very happily) surprised if it just works.

**Comment by dchelimsky** [comment]
Looking at those two api descriptors, the only op that actually interacts with a websocket is the `:PostToConnection` op in the `apigatewaymanagementapi` service. You can use that today following the directions [here](https://github.com/cognitect-labs/aws-api/#posttoconnection). Closing this issue, but feel free to continue the convo here or open a new issue if there is one.
