### ISSUE TITLE
Container credentials provider doesn't discover ECS Fargate creds

### ISSUE THREAD

**Issue by ghadishayban** [cognitect-labs/aws-api#33]
https://github.com/cognitect-labs/aws-api/blob/c43cc4527fa1d3f7873ad3fa1668c637b61890bb/src/cognitect/aws/credentials.clj#L220-L231

ECS should pull credentials from a _different_ endpoint than EC2 (169.254.170.2 vs 169.254.169.254 respectively)

**Comment by dchelimsky** [comment]
I've got a proposed fix on the `issue-33-ecs-creds` branch. In review.

**Comment by dchelimsky** [comment]
This is fixed on master but not yet released.

**Comment by dchelimsky** [comment]
Released in 0.8.198.
