### ISSUE TITLE
Missing region ap-northeast-3 - Asia Pacific (Osaka-Local) in endpoints

### ISSUE THREAD

**Issue by kennyjwilli** [cognitect-labs/aws-api#34]
The `endpoints.edn` is missing info on the `ap-northeast-3` region.

**Comment by dchelimsky** [comment]
We get our data from the aws-java-sdk: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json. Unfortunately, it's missing there. Same for the AWS CLI (botocore), aws-sdk-ruby, etc.

I see "**You can use the Asia Pacific (Osaka-Local) Region only in conjunction with the Asia Pacific (Tokyo) Region. To request access to the Asia Pacific (Osaka-Local) Region, contact your sales representative." on https://docs.aws.amazon.com/general/latest/gr/rande.html, so I wonder if they provide special SDKs for those customers.

Not quite sure what to do here, but I'm open to suggestions.

**Comment by dchelimsky** [comment]
Added to troubleshooting section of README.
