### ISSUE TITLE
Documentation / Guidance on handling errors

### ISSUE THREAD

**Issue by RickMoynihan** [cognitect-labs/aws-api#38]
I'm currently doing something like this:

```clojure
(defn invoke
  "Invokes the AWS request, converting any Error's into exceptions."
  [client req]
  (let [response (aws/invoke client req)]
    (if (:Error response)
      (throw (ex-info "Error invoking AWS service" response)) ;; if you want an exception out
      response)))
```

I'm assuming checking the existence of the `:Error` key is the right thing to do, but I've not seen it documented anywhere, so it would be nice to know that it can be consistently relied on for every request.

**Comment by dchelimsky** [comment]
Unfortunately, we haven't yet found a consistent way to manage this. There is an `:Errors` key on some, but not all operations. We do include a `:cognitect.anomalies/category` key whenever `(>= status 400)`, but many ops return 200 even when there are errors.  Specs for most ops include a description of errors in the specs, but about 10% don't.

I'll add some documentation about this to the readme.

**Comment by dchelimsky** [comment]
I added #39 to keep this on the radar even after we document it.

**Comment by RickMoynihan** [comment]
Thanks.

**Comment by devn** [comment]
+1, thanks for adding to the `README`. Hit a scenario with SageMaker where I assumed an exception to be thrown for a lack of permissions, but it was returning a map containing `:Errors` + `:cognitect.anomalies/category`. Would be nice if there was a uniform way to tackle errors!

**Comment by dchelimsky** [comment]
Hey - here's some fun news - the example in which I observed a 200 even with a missing key was an aws-api bug. See #56 for more detail. I've added a section on Responses to the README, so closing this.
