### ISSUE TITLE
Nested configuration values are not supported

### ISSUE THREAD

**Issue by sattvik** [cognitect-labs/aws-api#42]
As described in the [CLI documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#nested-values), some configuration values can have nested values.  As a result a line like the following in a `.aws/config` file will result in a NullPointerException when being parsed:

```
[default]
s3 =
	signature_version = s3v4
```

**Comment by dchelimsky** [comment]
You win just for logging issue #42!

**Comment by dchelimsky** [comment]
Fixed on master and will be part of next release.

**Comment by dchelimsky** [comment]
Released in 0.8.204.
