### ISSUE TITLE
Resource management

### ISSUE THREAD

**Issue by potetm** [cognitect-labs/aws-api#54]
# Problem
When working in the REPL, it's not uncommon to want to rebuild clients with different configurations. For example, you might want to try a different `:credentials-provider`, or change `:region`. The problem is that there is at least one long-lived resource in the client: the underlying `:http-client`. If you always create clients without cleaning up those resources, your development machine might run out of memory, sockets, etc.

In addition, it's generally a good idea to cleanup network connections on shutdown so other machines can immediately release resources instead of waiting for a timeout.

# Current workaround
```clj
(cognitect.http-client/stop
  (:http-client (cognitect.aws.client/-get-info c)))
```

This approach is problematic because `-get-info` is explicitly listed as internal-only:

```clj
(defprotocol ClientSPI
  (-get-info [_] "Intended for internal use only"))
```

# Suggested Solution
* Provide a `cognitect.aws.client.api/stop-client` fn that will release all resources

**Comment by dchelimsky** [comment]
Fixed on master, will be part of next release.
