### ISSUE TITLE
the stop function may stop the global default credentials-provider 

### ISSUE THREAD

**Issue by ghadishayban** [cognitect-labs/aws-api#57]
Introduced here, https://github.com/cognitect-labs/aws-api/commit/9960248aef88aaffb9b1831bdacfcb212941a86e , the stop function might accidentally stop the default https://github.com/cognitect-labs/aws-api/blob/a7d3184bb5f0e8eea2609b56de7d6d1ca6f2b36b/src/cognitect/aws/credentials.clj#L289 credentials provider, which is a global value behind a delay.

This will cause default credentials to stop refreshing.

**Comment by dchelimsky** [comment]
Proposed fix on https://github.com/cognitect-labs/aws-api/tree/daemonize-credentials-thread branch.

**Comment by dchelimsky** [comment]
Fix released in 0.8.271
