### ISSUE TITLE
ECS Fargate task won't STOP after execution

### ISSUE THREAD

**Issue by rlhk** [cognitect-labs/aws-api#58]
I have a Clojure app doing the following:
1. Connect to a Postgres DB, get some records
2. Generate a bunch of static html files
3. Put them to S3 bucket using aws-api

Everything is fine, including test running locally with `lein run ...`, `docker run ...` etc...
until I deploy it as an ECS Fargate task.

The task did run fine and finish by putting those S3 objects to the bucket. 
However the ECS task will stuck in RUNNING status forever unless manually stopped. As you could imagine, the ECS scheduler keep launching same task until the task limit is reached.

The same task can RUN & STOP as expected if I remove the code related to aws-api S3 putting while keeping the DB connection part.

So my question is: what's the difference between running a local docker and ECS Fargate tasks? Do we need to release the S3 client created by aws-api ? Any point is welcome. Thanks!

**Comment by rlhk** [comment]
Not sure if it's somehow related. I did once suspect the issue was related to `printf` flushing in my custom logger previously. The behaviour is different between `lein run...` and `docker run...`. This was resolved.

Seems to me the remaining and isolated culprit is aws-api s3 client.

**Comment by dchelimsky** [comment]
The credentials running in EC[2|S] keep a thread running to periodically refresh credentials. You should call [`cognitect.aws.client.api/stop`](https://cognitect-labs.github.io/aws-api/cognitect.aws.client.api-api.html#cognitect.aws.client.api/stop) before it shuts down. I'll leave this open as a reminder to make sure the docs are clear about this.

**Comment by dchelimsky** [comment]
I'm assuming, btw, that your docker uses env-configured credentials, which do not auto-refresh.

**Comment by rlhk** [comment]
Looks good in my docker run and cool to know the mechanics behind.

**Comment by rlhk** [comment]
Suggest to check this `nil` so that we can avoid errors, say when the credentials thread is not running / not available ?
```
Caused by: java.lang.IllegalArgumentException: No implementation of method: :-get-info of protocol: #'cognitect.aws.client/ClientSPI found for class: nil
```
Got the above error form my `lein run ...`

**Comment by dchelimsky** [comment]
Did calling `stop` solve the issue in ECS?

**Comment by rlhk** [comment]
Yes. Solved perfectly.

**Comment by dchelimsky** [comment]
FYI, we're going to make the credentials thread a daemon so you won't need the explicit stop again. I'll close this issue once that's released.

**Comment by dchelimsky** [comment]
Just released 0.8.271 with that change.

**Comment by gozes** [comment]
@dchelimsky it may just me but I'm seeing this when calling send-message on sqs

**Comment by dchelimsky** [comment]
@gozes I'm not really involved with this project any more. I'd recommend you open a new issue so it gets visibility.

**Comment by GabrielScotaCTF** [comment]
I'm still getting this behavior. In some standalone tasks that I start using boto3, my tasks do what they were supposed to do but sometimes some of them remains stuck as running...
I've configured a cron job to stop these tasks that are running for too long, but I wish to understand what is happening.

**Comment by scottbale** [comment]
Hi @GabrielScotaCTF,
Sorry to hear this. The original issue as logged _shouldn't_ still be an issue for you, if you're on version 0.8.271 or later - the thread pool which backs the default credentials fetcher was changed to spawn daemon threads. So the question becomes, what else could be causing similar symptoms? Are you providing your own `:credentials-provider`, overriding the default, and if so do you need to manage that provider (either invoking [stop](https://github.com/cognitect-labs/aws-api/blob/5900e359365041ed9380947d010b0f0a853e793c/src/cognitect/aws/credentials.clj#L110-L116) on the provider, or ensuring that any threads it uses are daemon threads)? Are you providing your own `:http-client`, overriding the default, and if so do you need to invoke [stop](https://github.com/cognitect-labs/aws-api/blob/5900e359365041ed9380947d010b0f0a853e793c/src/cognitect/aws/http.clj#L50-L55) on it, releasing any resources? Can you provide a code snippet that reproduces your issue?

**Comment by GabrielScotaCTF** [comment]
@scottbale Thanks for the reply! But I think I'm in the wrong project. Actually I'm using boto3 that uses aws api, so probably I'm not in the correct place to discuss it. Sorry for the inconvenience ;/
