### ISSUE TITLE
Requiring `cognitect.aws.client.api` from user ns fails

### ISSUE THREAD

**Issue by potetm** [cognitect-labs/aws-api#60]
If you have a `deps.edn`:

```clj
{:paths ["src"]
 :deps {com.cognitect.aws/api {:mvn/version "0.8.253"}
        org.clojure/clojure {:mvn/version "1.9.0"}}}
```

and a `src/user.clj`:

```clj
(ns user
 (:require [cognitect.aws.client.api :as aws]))
```

The following command:

```
clj -r
```

Fails with

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: clojure.edn, compiling:(cognitect/aws/service.clj:25:3)
```

It appears that there are a [few](https://github.com/cognitect-labs/aws-api/blob/a1f2bc4bbfd46ca69228976c53bec9d66197f37f/src/cognitect/aws/endpoint.clj#L16) [places](https://github.com/cognitect-labs/aws-api/blob/a1f2bc4bbfd46ca69228976c53bec9d66197f37f/src/cognitect/aws/service.clj#L25) that use `clojure.edn` without requiring it. This works most of the time, but not if you have requires (or transient requires) in your user ns.

**Comment by dchelimsky** [comment]
Released in 0.8.266
