### ISSUE TITLE
Anything like "aws s3 sync ... "?

### ISSUE THREAD

**Issue by rlhk** [cognitect-labs/aws-api#63]
I'm looking to sync a local folder to a s3 bucket, like what the aws cli tool can do: `aws s3 sync ...`.

Didn't find anything close in the aws-api lists, and looks like the s3.transfer is deprecated: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html

Any recommendation? Thanks!

**Comment by dchelimsky** [comment]
aws-api is designed to provide programatic access to AWS endpoints, but does not offer additional functionality that the SDKs provide, like `sync`, which is a complex operation comprising n calls to n endpoints. aws-api should provide you everything you need to write that op, but including it in the lib is outside of our scope.

This is a great example, btw, of an op that could be provided in a separate library, which we encourage!
