### ISSUE TITLE
Allow passing http-client config options to client function

### ISSUE THREAD

**Issue by dmarjenburgh** [cognitect-labs/aws-api#64]
I'm specifically interested in passing proxy-host and proxy-port, but in general it'd be nice if you could pass your own config into the http-client.

For example, like this:

```clj
(require '[cognitect.aws.client.api :as aws])
(aws/client {:api :s3
             :http-client-config {:proxy-host "10.0.30.40"
                                  :proxy-port 9400}})
```

**Comment by dchelimsky** [comment]
`:endpoint-override` map added in 0.8.280. You can supply `:protocol`, `:hostname`, `:port`, and `:path`.

**Comment by borgesgabriel** [comment]
I'm not sure that this issue has been fully addressed.

Referring back to @dmarjenburgh's ask, `proxy-host` and `proxy-port` create a `org.eclipse.jetty.client.Socks4Proxy`, and cannot be specified in `:endpoint-override` as far as I can tell.

**Comment by gzmask** [comment]
I agree with @borgesgabriel  . This is not the same thing.

**Comment by xiongtx** [comment]
See https://github.com/cognitect-labs/aws-api/issues/181#issuecomment-1461414333.
