### ISSUE TITLE
launch ec2 instance using LaunchTemplate

### ISSUE THREAD

**Issue by benkamphaus** [cognitect-labs/aws-api#68]
The command:

```clojure
(aws/invoke ec2 {:op :RunInstances
                   :request {:Instances {:LaunchTemplate template}}})
```

Fails with the error:

```
{:Response {:Errors {:Error {:Code "MissingParameter", :Message "The request must contain the parameter ImageId"}}, :RequestID "209fdf97-718e-4a64-891e-67d1ca40ecc8"}, :cognitect.anomalies/category :cognitect.anomalies/incorrect}
```

I can launch from the `aws ec2` CLI with only a template:

```
aws ec2 run-instances \
                                 --launch-template \
                                 "LaunchTemplateId="template-id",Version=7"

```

This is supported in the [Java AWS SDK](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/RunInstancesRequest.html#withLaunchTemplate-com.amazonaws.services.ec2.model.LaunchTemplateSpecification-l), when called with Clojure interop the minimal request looks like this:

```
(let [lt (.. (LaunchTemplateSpecification.)
             (withLaunchTemplateId template)
             (withVersion "7"))
      req (.. (RunInstancesRequest.)
            (withLaunchTemplate lt)
            (withMinCount (int 1))
            (withMaxCount (int 1)))
      ec2-client (AmazonEC2ClientBuilder/defaultClient)]
  (.runInstances ec2-client req))
```

Note this does require `withMinCount` and `withMaxCount` (differing from the CLI) but not the other params the Clojure AWS API complains are missing. (adding min and max params to Clojure invocation does not resolve the issue).

Tested with most recent (as of time of issue post) version of the API:

```
com.cognitect.aws/api       {:mvn/version "0.8.289"}
com.cognitect.aws/endpoints {:mvn/version "1.1.11.526"}
```

The version of the Java SDK for the example working invocation above was:

```
com.amazonaws/aws-java-sdk-ec2 {:mvn/version "1.11.349"}
```

It looks like from the [descriptor](https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ec2-2016-11-15.normal.json) that the Java SDK invocation requirements (min and max count always required, either manually provide sufficient fields like image-id etc. _or_ provide a launch template) correspond with the request description data:

```
    "RunInstancesRequest": {
      "type": "structure",
      "required": [
        "MaxCount",
        "MinCount"
      ],
```

But other than noting the `required` array contents I haven't dug deeper into the descriptor as of this time.

**Comment by benkamphaus** [comment]
User error including in `:Instances`:

```clojure
  (aws/invoke ec2 {:op :RunInstances
                   :request {:LaunchTemplate {:LaunchTemplateId template
                                              :LaunchTemplateVersion 7}
                             :MinCount 1
                             :MaxCount 1}}))
```

Where `template` is the string ID of the instance works. Feel free to close the issue.

**Comment by dchelimsky** [comment]
Thanks for following up @benkamphaus
