### ISSUE TITLE
Add `apropos` command

### ISSUE THREAD

**Issue by svantevonerichsen6906** [cognitect-labs/aws-api#75]
I'd like to get the correct dependency from the latest-releases.edn file from the REPL, e. g.:

    (aws/apropos "dynamodb")
    ⇒ [[com.cognitect.aws/dynamodb "697.2.391.0"]]

**Comment by dchelimsky** [comment]
That would be a nice convenience, but it raises more questions than it answers (where does the data come from? latest is on line, but what if we're offline? etc).
