### ISSUE TITLE
Latest release of EC2 fails to find service.edn

### ISSUE THREAD

**Issue by gregoriokusowski** [cognitect-labs/aws-api#78]
First of all, thank you for your work :)

When using `[com.cognitect.aws/ec2 "718.2.456.0"]` it fails with `Cannot find resource cognitect/aws/ec2/service.edn.`
Switching back to `[com.cognitect.aws/ec2 "716.2.439.0"]` solves the issue.

## Dependencies

```clojure
{:deps
  {com.cognitect.aws/api {:mvn/version "0.8.305"}}
  {com.cognitect.aws/endpoints {:mvn/version "1.1.11.553"}}
  {com.cognitect.aws/ec2 {:mvn/version "718.2.456.0"}}}"
```

## Description with failing test case

To spin up a clean environment for testing:

```
docker run --rm -it clojure:tools-deps bash
```

Spin up the repl with the versions:

```
clojure -Sdeps "{:deps {com.cognitect.aws/api {:mvn/version \"0.8.305\"}} {com.cognitect.aws/endpoints {:mvn/version \"1.1.11.553\"}} {com.cognitect.aws/ec2 {:mvn/version \"718.2.456.0\"}}}"
```

And then by running the [EC2 example](https://github.com/cognitect-labs/aws-api/blob/master/examples/ec2_examples.clj), the error is happening when building the client:

```clojure
(require '[cognitect.aws.client.api :as aws])

(def ec2 (aws/client {:api :ec2}))
```

## Stack traces

```
user=> user=> (def ec2 (aws/client {:api :ec2}))
Syntax error (ExceptionInfo) compiling at (REPL:1:10).
Cannot find resource cognitect/aws/ec2/service.edn.
```

**Comment by dchelimsky** [comment]
The map you're passing to the command has the keys `:deps` and `{com.cognitect.aws/endpoints {:mvn/version "1.1.11.553"}}`. This will fix it for you:

```
$ clojure -Sdeps "{:deps {com.cognitect.aws/api {:mvn/version \"0.8.305\"} com.cognitect.aws/endpoints {:mvn/version \"1.1.11.553\"} com.cognitect.aws/ec2 {:mvn/version \"718.2.456.0\"}}}"
Clojure 1.10.0
user=> (require '[cognitect.aws.client.api :as aws])
nil
user=> (def ec2 (aws/client {:api :ec2}))
2019-05-28 10:02:08.920:INFO::main: Logging initialized @19126ms
#'user/ec2```
