### ISSUE TITLE
DynamoDB retriable errors

### ISSUE THREAD

**Issue by deoqc** [cognitect-labs/aws-api#79]
## Dependencies

``` clojure
[org.clojure/clojure "1.10.0"]
[com.cognitect.aws/api "0.8.301"]
[com.cognitect.aws/endpoints "1.1.11.549"]
[com.cognitect.aws/dynamodb "697.2.391.0"]
```

## Description with failing test case

Not sure if is the intention to manually code the retriable exceptions.

I've encountered two different retriable exceptions in production (ProvisionedThroughputExceededException and InternalServerError) that were not being retriable here so I quickly mapped all of the from [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html).

Here the list:
```
"ProvisionedThroughputExceededException"
"ThrottlingException"
"RequestLimitExceeded"
"LimitExceededException"
"ItemCollectionSizeLimitExceededException"
"InternalServerError" ;; sometimes aws errors
"ServiceUnavailable"
```

If there is not intention to fix this, just close it.

Thx

**Comment by dchelimsky** [comment]
By default, we only retry when the status code is 503 or 504 (busy or unavailable). We haven't done anything using error codes because they are not described consistently across the 150+ service descriptors, so we'd have to write custom code for every operation on every service.

Regardless of whether we address this in the future, you can supply a custom `retriable?` fn today when you're building the client (see https://cognitect-labs.github.io/aws-api/cognitect.aws.client.api-api.html#cognitect.aws.client.api/client).

**Comment by deoqc** [comment]
Yeah I've read the source code and implemented an alternative `retriable?`.

I didn't rely on http code but on the error messages:
```
(defn ->error
  [http-response]
  (some-> http-response
          :__type
          (split #"#")
          second))

(defn retriable?
  [http-response]
  (or (retry/default-retriable? http-response)
      ;; add them all: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html
      (contains? #{"ProvisionedThroughputExceededException"  ;; returning :cognitect.anomalies/incorrect
                   "ThrottlingException"
                   "RequestLimitExceeded"
                   "LimitExceededException"
                   "ItemCollectionSizeLimitExceededException"
                   "InternalServerError" ;; sometimes aws errors
                   "ServiceUnavailable"}
                 (->error http-response))))
```

**Comment by dchelimsky** [comment]
FYI that works for ddb, and probably some other services, but not all of them (error codes vary across service).

**Comment by deoqc** [comment]
Sure.. Ok, will close it since as I understood "it is out of the scope of the library".

**Comment by dchelimsky** [comment]
Thanks!
