### ISSUE TITLE
Dynamic namespace loading can cause race conditions 

### ISSUE THREAD

**Issue by levand** [cognitect-labs/aws-api#92]
**Affected Component & Version:** `com.cognitect.aws/api 0.8.352`

**Problem Description**

It is possible to invoke `cognitect.aws.api/client` concurrently, such that the dynamically generated call to `require` on line 78 (https://github.com/cognitect-labs/aws-api/blob/v0.8.352/src/cognitect/aws/client/api.clj#L78) is also invoked concurrently.

This permits a race condition where, if namespace loading goes just wrong, can result in spurious `No such var` compile exceptions on otherwise straightforward code in the dynamically loaded namespaces.

**Proposed Solution**

Ensure that the dynamic call to `require` cannot be called in parallel, e.g by wrapping it in a `locking` form.

**Pre-patch workaround**

Ensure that calling code does not invoke `cognitect.aws.api/client` in parallel.

**Comment by dchelimsky** [comment]
Fixed in 5f6fdbdd997ec719917d318d1fc22e249aa971a5. Will close after released.

**Comment by dchelimsky** [comment]
Thanks, as always, @levand, for the descriptive and actionable report.

**Comment by dchelimsky** [comment]
Released in 0.8.378.
