### ISSUE TITLE
`cognitect.aws.region` uses incorrect environment variable name

### ISSUE THREAD

**Issue by ataggart** [cognitect-labs/aws-api#93]
#### Affected Component & Version
`com.cognitect.aws/api "0.8.352"`

#### Problem Description

`cognitect.aws.region/environment-region-provider` uses an incorrect environment variable name, `AWS_REGION`.

The [documented](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) environment variable name is `AWS_DEFAULT_REGION`.

The net result is an exception may be thrown (see below) despite a properly configured environment.

#### Stack trace

```
 {:type clojure.lang.ExceptionInfo,
  :message "No region found by any region provider.",
  :data
  {:providers
   (cognitect.aws.region$environment_region_provider$reify__14941
    cognitect.aws.region$system_property_region_provider$reify__14944
    cognitect.aws.region$profile_region_provider$reify__14947
    cognitect.aws.region$instance_region_provider$reify__14955)},
  :at
  [cognitect.aws.region$chain_region_provider$reify__14937
   fetch
   "region.clj"
   37]}],
:trace
[[cognitect.aws.region$chain_region_provider$reify__14937
  fetch
  "region.clj"
  37]
 [cognitect.aws.client.api$client invokeStatic "api.clj" 74]
 [cognitect.aws.client.api$client invoke "api.clj" 22]
```

#### Workaround

Add `AWS_REGION` to every environment.

**Comment by ataggart** [comment]
Related: https://github.com/aws/aws-cli/issues/735

**Comment by dchelimsky** [comment]
Confusingly, `AWS_REGION` is also [documented](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-region-selection.html) for the SDKs. 

We did try to convey this in our [docs](https://github.com/cognitect-labs/aws-api#region-lookup), by explicitly naming `AWS_REGION` and linking to the source AWS docs. Suggestions welcome if there's something you think we can do to make the docs more clear.

**Comment by ataggart** [comment]
@dchelimsky Would it be reasonable for it to also looking for the documented env var?

**Comment by ataggart** [comment]
>Confusingly, AWS_REGION is also documented for the SDKs.

@dchelimsky Yes, hence my earlier comment  linking to this: https://github.com/aws/aws-cli/issues/735#issuecomment-39395188

**Comment by dchelimsky** [comment]
> Would it be reasonable for it to also look for the `AWS_DEFAULT_REGION` env var?

Possibly, but then we get in the business of more cascading and conditional logic layered on top of AWS's. For me, that would be a more confusing outcome for users.

**Comment by ataggart** [comment]
@dchelimsky Just so I'm clear, this library will continue to only support the legacy `AWS_REGION` env var, despite current documentation and current official tooling giving primacy to `AWS_DEFAULT_REGION`, and thus consider this issue a documentation concern not an implementation concern?

**Comment by dchelimsky** [comment]
The current documentation for AWS SDKs uses `AWS_REGION`. There is nothing legacy about that. The current documentation for AWS CLI uses `AWS_DEFAULT_REGION`. We made a choice between conflicting recommendations from AWS, which we've documented in the README in this project.

We will certainly consider making a change when AWS makes a new recommendation for the SDKs.

**Comment by ataggart** [comment]
@dchelimsky Ah, ok, I wasn't mindful of the distinction between the SDK and CLI. Thanks for clearing that up.
