### ISSUE TITLE
Examples alias fails to load due to missing dependency

### ISSUE THREAD

**Issue by MageMasher** [cognitect-labs/aws-api#96]
# Outdated S3 dependency in `examples` alias
The current s3 dependency on master under the `examples` alias fails to download from maven.

```
clj -A:examples
Error building classpath. Could not find artifact com.cognitect.aws:s3:jar:746.2.533.0 in central (https://repo1.maven.org/maven2/)
```

Bumping the s3 dep to
```
com.cognitect.aws/s3        {:mvn/version "747.2.533.0"}
```
Succeeds!

# Other dependencies to update in the examples alias
```
com.cognitect.aws/endpoints {:mvn/version "1.1.11.636"}
com.cognitect.aws/ssm       {:mvn/version "747.2.533.0"}
com.cognitect.aws/sts       {:mvn/version "747.2.533.0"}
```

# All of the dependencies to update in the project (via https://github.com/Olical/depot)

Under the main `:deps`:
```
org.clojure/core.async      {:mvn/version "0.4.500"}
org.clojure/tools.logging   {:mvn/version "0.5.0"}
commons-codec/commons-codec {:mvn/version "1.13"}
```

Under the `:dev` alias:
```
commons-io/commons-io   {:mvn/version "2.6"}
org.slf4j/slf4j-log4j12 {:mvn/version "1.7.28"}
```

Under the `:test` alias:
```
{com.cognitect/test-runner {:git/url "https://github.com/cognitect-labs/test-runner.git" :sha "cb96e80f6f3d3b307c59cbeb49bb0dcb3a2a780b"}}
```

Under the `examples` alias:
```
org.slf4j/slf4j-log4j12 {:mvn/version "1.7.28"}
com.cognitect.aws/endpoints {:mvn/version "1.1.11.636"}
com.cognitect.aws/s3 {:mvn/version "747.2.533.0"}
com.cognitect.aws/ssm {:mvn/version "747.2.533.0"}
com.cognitect.aws/sts {:mvn/version "747.2.533.0"}}
```

**Comment by dchelimsky** [comment]
Thank you for this report!

I've already updated the s3 and endpoints deps, but the depot report is incorrect about some of the others:

* https://search.maven.org/search?q=g:org.clojure%20AND%20a:core.async shows 0.4.500 as the latest release
* https://search.maven.org/search?q=g:com.cognitect.aws%20AND%20a:ssm shows 747.2.533.0 as the latest release

I'll leave this open while I do some more digging.

**Comment by MageMasher** [comment]
Oh, I'm so sorry @dchelimsky , the snippets refer to all of the dependencies that depot *updated*, not that they are out of date. Apologies for the confusion, I was still waking up when I made the report.

**Comment by MageMasher** [comment]
I've changed the language in the headers. I only listed the latest version of all the dependencies, the absence of a dependency means it is already at its latest version.

**Comment by dchelimsky** [comment]
OK - I've updated all the deps.

FYI, while looking into this, I discovered and reported a couple of issues:
* https://github.com/Olical/depot/issues/33
* https://github.com/Olical/depot/issues/34
